SRG-APLExamenes/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data;
using SRG_APLExamenes.Models.Assistant;
using SRG_APLExamenes.Models.Deal;

namespace SRG_APLExamenes.Controllers
{
    [SessionExpire]
    [Authorize]
    public class MenuController : Controller
    {
        public PartialViewResult ConstruirMenu()
        {
            Mdl_Accesos Controlador = new Mdl_Accesos();
            DataTable Dt_Accesos = new DataTable();
            if (!String.IsNullOrEmpty(SessionSRG.No_Empleado.ToString()))
            {
                Controlador.No_Empleado = SessionSRG.No_Empleado.ToString();
                Dt_Accesos = Controlador.Consult();
            }
            return PartialView(Dt_Accesos);
        }
    }
}

SRG-APLExamenes/Views/Shared/Admin_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" type="image/png" href="~/Content/Image/favicon_admin.ico" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap-4.1.1-dist/css/bootstrap.min.css")
    @Styles.Render("~/Content/Administracion.css")
    @Styles.Render("~/Content/themes/Menu/jquery-slide-menu.css")
    @Styles.Render("~/Content/themes/Modal/popModal.min.css")
    @Styles.Render("~/Content/themes/Select/select2.min.css")
    @Styles.Render("~/Content/Fonts/fontawesome-free-5.10.1/css/all.min.css")
    @Styles.Render("~/Content/themes/Datatable/datatables.min.css")
    @Styles.Render("~/Content/themes/Datatable/buttons.dataTables.min.css")
    @Styles.Render("~/Content/themes/Datatable/select.dataTables.min.css")
    @Styles.Render("~/Content/bootstrap-datepicker-1.6.4-dist/css/bootstrap-datepicker.min.css")
    @Styles.Render("~/Content/bootstrap-datetimepicker-0.0.11/css/bootstrap-timepicker.min.css")
    @RenderSection("style", required: false)

</head>
<body>
    <!-- Navigation -->
    <!-- Page Content -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-2">
                <div class="list-group">
                    @{Html.RenderAction("ConstruirMenu", "Menu");}
                </div>
                <hr />
                <div class="row text-center">
                    <div class="col-lg-6">
                        <button type="button" class="btn btn-primary btn3d" onclick="location.href='@Url.Action("Inicio", "Administracion")'"><i class="fa fa-home"> Inicio</i></button>
                        @*<button type="button" class="btn btn-success btn-circle btn-xl" onclick="location.href='@Url.Action("Inicio", "Administracion")'"><i class="fa fa-home"></i></button>*@
                    </div>
                    <div class="col-lg-6">
                        @using (Html.BeginForm("Salir", "Administracion"))
                        {
                            <button type="submit" class="btn btn-danger  btn3d"><i class="fas fa-sign-out-alt"> Salir</i></button>
                            @*<button type="submit" class="btn btn-warning btn-circle btn-xl"><i class="fas fa-sign-out-alt"></i></button>*@
                        }
                    </div>
                </div>
                <hr />
            </div>
            @RenderBody()
        </div>
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-7">
                        <p class="m-0 text-left text-white">&copy;<span id="year"></span> Todos los derechos reservados.</p>
                    </div>
                    <div class="col-lg-5">
                        <p id="St-Map" class="m-0 text-right text-white">Site Map: /Principal</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="content" style="display: none;">
    </div>

    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/Scripts/jquery-migrate-3.0.0.js")
    @Scripts.Render("~/Content/bootstrap-4.1.1-dist/js/bootstrap.bundle.min.js")
    @Scripts.Render("~/Content/bootstrap-4.1.1-dist/js/bootstrap.min.js")
    @Scripts.Render("~/Scripts/themes/jquery-slide-menu.js")
    @Scripts.Render("~/Scripts/themes/popModal.min.js")
    @Scripts.Render("~/Scripts/themes/select2.min.js")
    @Scripts.Render("~/Scripts/themes/datatables.min.js")
    @Scripts.Render("~/Scripts/themes/dataTables.buttons.min.js")
    @Scripts.Render("~/Scripts/themes/dataTables.select.min.js")
    @Scripts.Render("~/Scripts/themes/ajaxupload.3.5.js")
    @Scripts.Render("~/Scripts/themes/jquery.toast.js")
    @Scripts.Render("~/Content/bootstrap-datepicker-1.6.4-dist/js/bootstrap-datepicker.min.js")
    @Scripts.Render("~/Content/bootstrap-datetimepicker-0.0.11/js/bootstrap-timepicker.min.js")
    @Scripts.Render("~/Content/Plugins/sweetalert2_8.js")
    @Scripts.Render("~/Content/Plugins/moment.min.js")
    @Scripts.Render("~/Scripts/Utiles/Validaciones.js?v=1.0.1")
    <script type="text/javascript">
        $(document).ready(function (e) {
            $('.nav-slide').SlideMenu();
            $("#year").text((new Date).getFullYear());
        });

    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

SRG-APLExamenes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" type="image/png" href="~/Content/Image/favicon.ico" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap-4.1.1-dist/css/bootstrap.min.css")
    @Styles.Render("~/Content/Recursos/xenon/css/xenon-skins.css")
    @Styles.Render("~/Content/Recursos/xenon/css/custom.css")
    @Styles.Render("~/Content/Site.css")

</head>
    <body class="page-body login-page" cz-shortcut-listen="true">
        <div id="login-container" class="login-container" >
            <div class="row justify-content-lg-center">
                <div class="col-sm-6 col-sm-offset-3">
                    <!-- Errors container -->
                    <div class="errors-container"></div>

                    <!-- Add class "fade-in-effect" for login form effect -->
                    <form method="post" role="form" id="login" class="login-form fade-in-effect in" novalidate="novalidate">

                        <div class="login-header" style="margin-bottom:20px !important">
                            <div class="row">
                                <div class="col-md-12">
                                    <img src="/Content/Image/logo_empresa.jpg" style="width: 60%; height: 60%; margin:5% 20%">

                                </div>
                                <div class="col-md-12">
                                    <span class="h2" style="">MODULOS SISTEMAS</span>

                                    <p>Ingresa tus datos para accesar al sistema.</p>
                                </div>
                            </div>
                        </div>                        
                        <div id="login-usuario" class="row" style="display:block;">
                            @RenderBody()
                        </div>                        
                    </form>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modal_recuperar_password" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title" id="myModalLabel">Recuperar contraseña</h4>
                    </div>
                    <div class="modal-body">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="text-center">
                                    <h3><i class="fa fa-lock fa-4x"></i></h3>
                                    <h2 class="text-center">Recuperar Password</h2>
                                    <p>Enviaremos su password a la cuenta de correo que se configuró al registrarse.</p>
                                    <div class="panel-body">

                                        <form class="form">
                                            <fieldset>
                                                <div class="form-group">
                                                    <div class="input-group">
                                                        <span class="input-group-addon">
                                                            <i class="glyphicon glyphicon-envelope color-blue"></i>
                                                        </span>

                                                        <input class="form-control fix-form-control" id="emailInput" required="" onchange="try{setCustomValidity('')}catch(e){}" oninvalid="setCustomValidity('Por favor ingresar una dirección de correo válida!')" type="email" placeholder="email">
                                                    </div>
                                                </div>
                                                <div class="form-group">

                                                    <button id="btn_enviar_email" class="btn btn-lg btn-primary  btn-block btn-icon btn-icon-standalone btn-icon-standalone-right" type="submit">
                                                        <i class="fa fa-paper-plane" aria-hidden="true"></i>
                                                        <span>Enviar</span>
                                                    </button>
                                                </div>
                                            </fieldset>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </body>
    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/Scripts/jquery-migrate-3.0.0.js")
    @Scripts.Render("~/Content/bootstrap-4.1.1-dist/js/bootstrap.bundle.min.js")
    @Scripts.Render("~/Content/bootstrap-4.1.1-dist/js/bootstrap.min.js")
    <script type="text/javascript">
        $(document).ready(function (e) {
            $("#year").text((new Date).getFullYear());
        });

    </script>
    @RenderSection("scripts", required: false)
</body>
</html>